name: CI Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest   # Required to specify a runner
    steps:
      - name: 23f3001596@ds.study.iitm.ac.in
        run: echo "Hello, world!"

